import { ArrowLeft, CheckCircle2, CircleDashed, LockKeyhole, ShieldCheck, Stethoscope } from 'lucide-react';
import { Link } from 'react-router-dom';

const areas = [
  { title: 'Application safeguards', status: 'Ready for synthetic pilot', ready: true, detail: 'Quality checks, production safety gates, request validation, audit foundations, and secure response headers are in place.' },
  { title: 'Clinic and legal approval', status: 'Clinic decision required', ready: false, detail: 'Privacy notice, consent language, retention schedule, risk review, and controlled-pilot authorization need named owners and approval dates.' },
  { title: 'Vendors and BAAs', status: 'Provider selection required', ready: false, detail: 'Hosting, database, identity, calendar, messaging, and monitoring services must be approved before they receive patient information.' },
  { title: 'Identity and access', status: 'Real provider required', ready: false, detail: 'Staff MFA, secure account recovery, device/session management, and periodic access reviews depend on Stage 1 identity integration.' },
  { title: 'Operations and recovery', status: 'Exercise required', ready: false, detail: 'Choose alert owners, approve incident contacts, configure encrypted backups, and record a successful isolated restore test.' },
  { title: 'Pilot launch', status: 'Synthetic data only', ready: true, detail: 'The current release is appropriate for demonstrations and staff walkthroughs using fictional patients only.' },
];

export default function PilotReadinessPage() {
  return <main className="min-h-screen bg-slate-50 px-4 py-8 sm:px-6"><div className="mx-auto max-w-5xl"><Link to="/admin" className="inline-flex min-h-11 items-center gap-2 rounded-xl px-3 text-sm font-medium text-slate-600 hover:bg-white hover:text-slate-950"><ArrowLeft size={18} /> Back to clinician dashboard</Link><header className="mt-5 overflow-hidden rounded-3xl bg-slate-950 p-7 text-white shadow-xl sm:p-10"><div className="flex flex-wrap items-start justify-between gap-6"><div className="max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-blue-300">Controlled pilot readiness</p><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Safe progress, clearly documented</h1><p className="mt-4 max-w-xl leading-relaxed text-slate-300">ZONA PT is ready for a synthetic-data clinic walkthrough. Real patient information stays blocked until the clinic approves its vendors, policies, identity controls, and recovery evidence.</p></div><span className="grid h-16 w-16 place-items-center rounded-2xl bg-blue-600"><ShieldCheck size={32} /></span></div><div className="mt-7 inline-flex items-center gap-2 rounded-full border border-amber-300/30 bg-amber-300/10 px-4 py-2 text-sm font-semibold text-amber-100"><LockKeyhole size={17} /> PHI production mode is off</div></header><section aria-labelledby="readiness-heading" className="mt-8"><div className="flex items-center gap-3"><Stethoscope className="text-blue-700" /><h2 id="readiness-heading" className="text-2xl font-semibold tracking-tight text-slate-950">Readiness overview</h2></div><div className="mt-5 grid gap-4 md:grid-cols-2">{areas.map((area) => <article key={area.title} className="surface-card p-6"><div className="flex items-start gap-3">{area.ready ? <CheckCircle2 className="mt-0.5 shrink-0 text-emerald-600" /> : <CircleDashed className="mt-0.5 shrink-0 text-amber-600" />}<div><h3 className="font-semibold text-slate-950">{area.title}</h3><p className={`mt-1 text-sm font-semibold ${area.ready ? 'text-emerald-700' : 'text-amber-700'}`}>{area.status}</p><p className="mt-3 text-sm leading-relaxed text-slate-600">{area.detail}</p></div></div></article>)}</div></section><aside className="mt-8 rounded-2xl border border-blue-200 bg-blue-50 p-6"><h2 className="font-semibold text-blue-950">Client presentation note</h2><p className="mt-2 text-sm leading-relaxed text-blue-900">During demonstrations, describe this as a secure patient-engagement prototype undergoing controlled-pilot preparation—not as a certified EHR or completed HIPAA compliance program.</p></aside></div></main>;
}
